/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/shared/Button/Button.vue')['default']
    Card: typeof import('./../src/components/shared/Card/Card.vue')['default']
    Drawer: typeof import('./../src/components/suggestions/Drawer/Drawer.vue')['default']
    Dropdown: typeof import('./../src/components/shared/Dropdown/Dropdown.vue')['default']
    Empty: typeof import('./../src/components/suggestions/Empty/Empty.vue')['default']
    FilterCard: typeof import('./../src/components/suggestions/FilterCard/FilterCard.vue')['default']
    Footer: typeof import('./../src/components/shared/Footer/Footer.vue')['default']
    GradientHeader: typeof import('./../src/components/suggestions/GradientHeader/GradientHeader.vue')['default']
    Navbar: typeof import('./../src/components/suggestions/Navbar/Navbar.vue')['default']
    PRCard: typeof import('./../src/components/suggestions/PRCard/PRCard.vue')['default']
    RoadmapCard: typeof import('./../src/components/suggestions/RoadmapCard/RoadmapCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuggestionsHeader: typeof import('./../src/components/suggestions/SuggestionsHeader/SuggestionsHeader.vue')['default']
  }
}
